version: "3.4"
services:
  pg-primary:
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
      args:
        - PG_PRIMARY=true
    environment:
      # - "POSTGRES_PASSWORD=testpass"
      - "PG_PRIMARY=true"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5433:5432"
  pg-secondary:
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    depends_on:
      - pg-primary
    environment:
      - "POSTGRES_PASSWORD=testpass"
    ports:
      - "5434:5432"
