# TODO: needs improvements as currentlly ` docker-compose up -d --build` has to be run twice
# as replication init on secodary doen't work 100% properly
version: "3.4"
services:
  pg-primary:
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    environment:
      - "POSTGRES_PASSWORD=testpass"
      - "PG_PRIMARY=true"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "PG_REPLICATION=true"
    ports:
      - "5433:5432"
  pg-secondary:
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    depends_on:
      - pg-primary
    environment:
      - "POSTGRES_PASSWORD=testpass"
      - "PG_REPLICATION=true"
    ports:
      - "5434:5432"
